# Generated by Django 5.2 on 2026-02-08 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='อายุ (ปี)')),
                ('weight', models.FloatField(verbose_name='น้ำหนัก (กก.)')),
                ('height', models.FloatField(verbose_name='ส่วนสูง (ซม.)')),
                ('gender', models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], default='F', max_length=1, verbose_name='เพศ')),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'น้อย (นั่งทำงานเป็นหลัก/ไม่ออกกำลังกาย)'), ('LIGHTLY', 'ปานกลาง (ออกกำลังกาย 1-3 วัน/สัปดาห์)'), ('MODERATE', 'ปานกลางค่อนข้างหนัก (ออกกำลังกาย 3-5 วัน/สัปดาห์)'), ('VERY', 'หนัก (ออกกำลังกาย 6-7 วัน/สัปดาห์)'), ('EXTRA', 'หนักมาก (นักกีฬา/ทำงานใช้แรงงาน)')], default='SEDENTARY', max_length=10, verbose_name='ระดับกิจกรรม')),
                ('bust', models.FloatField(verbose_name='รอบอก (ซม.)')),
                ('waist', models.FloatField(verbose_name='รอบเอว (ซม.)')),
                ('hip', models.FloatField(verbose_name='รอบสะโพก (ซม.)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='ค่า BMI')),
                ('bmi_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='เกณฑ์ BMI')),
                ('whr', models.FloatField(blank=True, null=True, verbose_name='WHR (Waist-to-Hip Ratio)')),
                ('body_shape', models.CharField(blank=True, max_length=50, null=True, verbose_name='รูปร่าง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'ผลการวิเคราะห์รูปร่าง',
                'verbose_name_plural': 'ผลการวิเคราะห์รูปร่าง',
            },
        ),
    ]
